[project]
name = "project-se2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">3.12"
dependencies = [
    "altair[all]>=5.4.1",
    "ipykernel>=6.29.5",
    "kagglehub>=0.3.4",
    "polars>=1.14.0",
    "streamlit>=1.40.1",
]
